In [18]:
import numpy as np
A = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
A

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [19]:
A.shape

(3, 4)

In [20]:
u, o, vt = np.linalg.svd(A)

In [21]:
u

array([[-0.25074393, -0.87775897,  0.40824829],
       [-0.53030989, -0.22826465, -0.81649658],
       [-0.80987586,  0.42122967,  0.40824829]])

In [22]:
o

array([2.11562535e+01, 1.55336357e+00, 7.11111853e-16])

error uploading: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E762F4EC70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
