In [15]:
import numpy as np
import pandas as pd

In [16]:
df = pd.read_csv(r"D:\Arjun 2\Coding Files-Arjun\Computer Science\College\IntroToML\1. TEE\PCA\PCA_case study.csv")
df

Manufacture    Model   Sales  Resales  Type  Price  Engine_size  Horsepow  \
0         Acura  Integra  16.919   16.360     0  21.50          1.8     140.0   
1         Acura       TL  39.384   19.875     0  28.40          3.2     225.0   
2         Acura       CL  14.114   18.225     0    NaN          3.2     225.0   
3         Acura       RL   8.588   29.725     0  42.00          3.5     210.0   
4          Audi       A4  20.397   22.255     0  23.99          1.8     150.0   
..          ...      ...     ...      ...   ...    ...          ...       ...   
152       Volvo      V40   3.545      NaN     0  24.40          1.9     160.0   
153       Volvo      S70  15.245      NaN     0  27.50          2.4     168.0   
154       Volvo      V70  17.531      NaN     0  28.80          2.4     168.0   
155       Volvo      C70   3.493      NaN     0  45.50          2.3     236.0   
156       Volvo      S80  18.969      NaN     0  36.00          2.9     201.0   

     WheelBase  Width  Length  Curb_Wgt  Fuel_Cap   Mpg  Inslaes  
0        101.2   67.3   172.4     2.639      13.2  28.0     2.83  
1        108.1   70.3   192.9     3.517      17.2  25.0     3.67  
2        106.9   70.6   192.0     3.470      17.2  26.0     2.65  
3        114.6   71.4   196.6     3.850      18.0  22.0     2.15  
4        102.6   68.2   178.0     2.998      16.4  27.0     3.02  
..         ...    ...     ...       ...       ...   ...      ...  
152      100.5   67.6   176.6     3.042      15.8  25.0     1.27  
153      104.9   69.3   185.9     3.208      17.9  25.0     2.72  
154      104.9   69.3   186.2     3.259      17.9  25.0     2.86  
155      104.9   71.5   185.7     3.601      18.5  23.0     1.25  
156      109.9   72.1   189.8     3.600      21.1  24.0     2.94  

[157 rows x 15 columns]

In [17]:
from sklearn.decomposition import PCA
A = np.array([[1,3],[1,2],[2,3],[0,3],[5,4],[4,5],[5,5],[3,4]])
print(A)

[[1 3]
 [1 2]
 [2 3]
 [0 3]
 [5 4]
 [4 5]
 [5 5]
 [3 4]]


In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Manufacture  157 non-null    object 
 1   Model        157 non-null    object 
 2   Sales        157 non-null    float64
 3   Resales      121 non-null    float64
 4   Type         157 non-null    int64  
 5   Price        155 non-null    float64
 6   Engine_size  156 non-null    float64
 7   Horsepow     156 non-null    float64
 8   WheelBase    156 non-null    float64
 9   Width        156 non-null    float64
 10  Length       156 non-null    float64
 11  Curb_Wgt     155 non-null    float64
 12  Fuel_Cap     156 non-null    float64
 13  Mpg          154 non-null    float64
 14  Inslaes      157 non-null    float64
dtypes: float64(12), int64(1), object(2)
memory usage: 18.5+ KB


In [19]:
df = df.iloc[:,5:-1].dropna()
df

Price  Engine_size  Horsepow  WheelBase  Width  Length  Curb_Wgt  \
0    21.50          1.8     140.0      101.2   67.3   172.4     2.639   
1    28.40          3.2     225.0      108.1   70.3   192.9     3.517   
3    42.00          3.5     210.0      114.6   71.4   196.6     3.850   
4    23.99          1.8     150.0      102.6   68.2   178.0     2.998   
5    33.95          2.8     200.0      108.7   76.1   192.0     3.561   
..     ...          ...       ...        ...    ...     ...       ...   
152  24.40          1.9     160.0      100.5   67.6   176.6     3.042   
153  27.50          2.4     168.0      104.9   69.3   185.9     3.208   
154  28.80          2.4     168.0      104.9   69.3   186.2     3.259   
155  45.50          2.3     236.0      104.9   71.5   185.7     3.601   
156  36.00          2.9     201.0      109.9   72.1   189.8     3.600   

     Fuel_Cap   Mpg  
0        13.2  28.0  
1        17.2  25.0  
3        18.0  22.0  
4        16.4  27.0  
5        18.5  22.0  
..        ...   ...  
152      15.8  25.0  
153      17.9  25.0  
154      17.9  25.0  
155      18.5  23.0  
156      21.1  24.0  

[152 rows x 9 columns]

In [20]:
pca = PCA(0.95)

In [21]:
pca.fit(df)

PCA(n_components=0.95)

In [22]:
print(pca.components_.T)

[[ 0.20965492 -0.24613362]
 [ 0.0150626   0.0183618 ]
 [ 0.97023411 -0.05739363]
 [ 0.03943286  0.45130354]
 [ 0.03224901  0.13697029]
 [ 0.09214271  0.8313463 ]
 [ 0.0068021   0.01957799]
 [ 0.03498288  0.12297828]
 [-0.04591736 -0.08190044]]


In [23]:
pca.explained_variance_

array([3426.41556232,  212.40791366])

In [24]:
pca.explained_variance_ratio_

array([0.9197554 , 0.05701682])

In [25]:
D = pca.fit_transform(df)

In [26]:
D

array([[-4.67972915e+01, -1.24661676e+01],
       [ 3.96817297e+01,  2.30506677e+00],
       [ 2.87847628e+01,  6.33478757e+00],
       [-3.58123758e+01, -7.75987965e+00],
       [ 1.68947414e+01,  3.08995386e+00],
       [ 1.30425673e+02, -2.56630875e+00],
       [-1.57065410e+01, -9.03743207e+00],
       [ 8.05243238e+00, -1.17518432e+01],
       [ 1.05727401e+01, -7.93207071e-01],
       [-9.89950376e+00,  8.93648758e+00],
       [ 5.41138133e+01,  5.89774169e+00],
       [ 2.27741220e+01,  1.75641852e+01],
       [ 2.11081958e+01,  1.18202657e+01],
       [ 9.25478750e+01,  1.27592971e+01],
       [ 9.16524748e+01,  4.23032285e+00],
       [ 1.62849912e+01,  4.70650909e+00],
       [ 7.48359631e+01,  1.07353182e+01],
       [-7.17731078e+01, -3.20534127e-01],
       [-1.65530974e+01,  5.40250720e+00],
       [-1.00631323e+01,  1.41175177e+01],
       [-5.33206877e+00,  1.24858433e+01],
       [ 1.44437658e+01,  2.31146919e+00],
       [ 1.58725869e+02, -2.04687191e+01],
       [-6.